### ISSUE TITLE
Улучшить время работы ручки api/1/2/3/get_task

### ISSUE THREAD

**Issue by ZhNV2** [Qwsafex/sphere#10]
## Описание дефекта

Было обнаружено, что при вызове ручки сервера api/1/2/3/get_task на тестовых  таблицах размером около 20 тысяч задач метод начинает работать больше 2 секунд, что неприемлемо для таких небольших данных. Надо разобраться, что именно тормозит (скорее всего дело в архитектуре базы), может стоит попробовать добавить каких-нибудь index-ов.

## Контекст

тест проявился на сборках
server 1.02-develop

## Ссылки

тестовые данные (ref:)
вывод explain analyze (ref:)

**Comment by Qwsafex** [comment]
Пока решили не добавлять индексы, а разбить таблицу Tasks на Task и User_Task. @KatyaKos сделай, пожалуйста

**Comment by KatyaKos** [comment]
Сделала. Теперь укладывается в 0.1 секунду.
[build](url)

**Comment by ZhNV2** [comment]
все ок

**Comment by ZhNV2** [comment]
Та же проблема возникла из-за ....
Сейчас на этом (ref:) работает снова порядка 2 секунд
Наверное, надо все-таки индексов надобавлять

**Comment by KatyaKos** [comment]
Хорошо, добавлю индексы. @ZhNV2

**Comment by KatyaKos** [comment]
Сделала. Стало работать в среднем за 0.8 сек.
[build](url)

**Comment by ZhNV2** [comment]
ок
