### ISSUE TITLE
Введение ограничения на количество заданий за временной промежуток

### ISSUE THREAD

**Issue by KatyaKos** [Qwsafex/sphere#14]
## Описание

Во многих приложениях у пользователей есть так называемая энергия. Она нужна, чтобы продолжить игру, например. При этом энергию можно докупать за реальные деньги или купить премиум аккаунт, в котором ее нет.

В сфере можно сделать что-то подобное. Например, за день игроки могут выполнить по два задания каждого типа сложности. Это вряд ли повлияет на пользователей, использующих приложение просто для развлечения. Но профессиональные игроки станут покупать премиум аккаунты и специальные возможности. Что принесет нашей компании деньги.

## Контекст
front 2.7
back 1.4
server 1.03-develop

**Comment by ZhNV2** [comment]
Не уверен, что хорошая идея. 
Лишняя монетизация не всегда хороший ход, так как многих пользователей это может отпугнуть.
Но мы вас услышали,  решили добавить в список вопросов на пятничной встрече (ref:).

**Comment by ZhNV2** [comment]
Провели встречу, решили не делать.
