### ISSUE TITLE
При первоначальной загрузке чата стрима показывается верх чата

### ISSUE THREAD

**Issue by ZhNV2** [Qwsafex/sphere#7]
## Описание дефекта

При первом подключении к стриму (когда чат еще не кешировался) чат отображает не конец чата (то есть последние актуальные сообщения), а самое начало истории, и поэтому приходится руками листать вниз до конца.
Кажется, что все-таки будет интереснее показывать пользователю именно низ, а если он хочет посмотреть начало, пусть листает сам вверх.

## Контекст

тест проявился на сборках
front 2.68
back 1.36
server 1.02-develop

**Comment by KatyaKos** [comment]
Да, согласна, чат нужно показывать с новых сообщений. @Qwsafex, почему у нас не так? Исправьте, пожалуйста. @ZhNV2 спасибо, что обратили внимание.

**Comment by Qwsafex** [comment]
Исправил. [Билд](http://sphere.teamcity.net/for_kolya)

**Comment by ZhNV2** [comment]
Проблема действительно перестала проявляться на всех тестовых телефонах, но всплыла при тесте на планшете (например, ref:)

**Comment by Qwsafex** [comment]
Исправил на планшетах ([билд](sphere.teamcity.net/final_kolya))

**Comment by ZhNV2** [comment]
все работает, спасибо!)
